version: '3.8'

services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile.bot
    volumes:
      - db_volume:/data
      - ./bot:/app
    environment:
      - PYTHONUNBUFFERED=1
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "1"
    healthcheck:
      disable: true

  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    ports:
      - "8063:8000"
    volumes:
      - db_volume:/data
      - ./api:/app
    environment:
      - PYTHONUNBUFFERED=1
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "1"
    healthcheck:
      disable: true

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "3063:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_API_URL=http://localhost:8063
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "1"
    healthcheck:
      disable: true

volumes:
  db_volume:
    driver: local
